// Builds the static GitHub Pages copy of the public site into .pages-build/out
// (used by `npm run deploy`, which then publishes it with gh-pages).
//
// GitHub Pages only serves static files, so the build copies the project into .pages-build/
// without the server-only parts (app/api, app/media, the staff sign-in and dashboard) - your
// working tree is never touched - and runs `next build` there with STATIC_EXPORT=1
// (static export + basePath, see next.config.ts). Two modes:
//
//  - Standalone demo (no PAGES_API_URL): no server needed. Tours, places, blogs and the header menu
//    are saved as JSON (demo-api/*.json) and uploaded images are downloaded from FTP into media/.
//    Forms (enquiry, contact, subscribe) and staff sign-in are switched off.
//  - With PAGES_API_URL (the Hostinger site): API calls, images and Sign In go to that server.
//
// Data is read from the database at build time, so re-deploy after adding tours, places or blogs.
import { cpSync, createWriteStream, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync, copyFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { Client } from 'basic-ftp';
import { loadEnv, projectRoot } from './_env.mjs';

const env = { ...(existsSync(path.join(projectRoot, '.env')) ? loadEnv() : {}), ...process.env };
const apiUrl = (env.PAGES_API_URL || '').replace(/\/+$/, '');
if (apiUrl && !/^https?:\/\//.test(apiUrl)) {
  console.error('PAGES_API_URL must be a full URL, e.g. https://exporioholidays.com (or leave it empty for the standalone demo)');
  process.exit(1);
}
const demo = !apiUrl;

/** Few, patient database connections during the build (shared Hostinger MySQL is slow to accept new ones). */
function limitConnections(url) {
  if (!url) return url;
  const extra = { connection_limit: '2', connect_timeout: '30', pool_timeout: '60' };
  const params = Object.entries(extra).filter(([k]) => !url.includes(`${k}=`)).map(([k, v]) => `${k}=${v}`);
  return params.length ? `${url}${url.includes('?') ? '&' : '?'}${params.join('&')}` : url;
}

const buildDir = path.join(projectRoot, '.pages-build');
const outDir = path.join(buildDir, 'out');
// Server-only parts; GitHub Pages can't run them
const SKIP = new Set(['node_modules', '.git', '.next', 'out', '.pages-build', 'app/api', 'app/media', 'app/auth', 'app/admin', 'app/sitemap.ts', 'app/robots.ts', 'middleware.ts']);

rmSync(buildDir, { recursive: true, force: true });
const keep = (src) => {
  const rel = path.relative(projectRoot, src).split(path.sep).join('/');
  return !(SKIP.has(rel) || rel.startsWith('.next-'));
};
// Copy entry by entry (Node refuses to copy a folder into its own subfolder)
for (const entry of readdirSync(projectRoot)) {
  const src = path.join(projectRoot, entry);
  if (keep(src)) cpSync(src, path.join(buildDir, entry), { recursive: true, filter: keep });
}

// Demo: static JSON "API" files, generated by Next from the same data functions the real API uses
const DEMO_API = {
  'tours.json': `import { getAllTours } from '@/lib/data';\nexport const dynamic = 'force-static';\nexport async function GET() { return Response.json(await getAllTours()); }\n`,
  'destinations.json': `import { getAllDestinations } from '@/lib/data';\nexport const dynamic = 'force-static';\nexport async function GET() { return Response.json(await getAllDestinations()); }\n`,
  'blogs.json': `import { getAllBlogs } from '@/lib/data';\nexport const dynamic = 'force-static';\nexport async function GET() { return Response.json(await getAllBlogs()); }\n`,
  'menu.json': `import { getMenu } from '@/lib/data';\nexport const dynamic = 'force-static';\nexport async function GET() { return Response.json(await getMenu()); }\n`,
};
if (demo) {
  for (const [file, code] of Object.entries(DEMO_API)) {
    mkdirSync(path.join(buildDir, 'app', 'demo-api', file), { recursive: true });
    writeFileSync(path.join(buildDir, 'app', 'demo-api', file, 'route.ts'), code);
  }
}

console.log(demo ? 'Building the standalone GitHub Pages demo (no server) ...' : `Building the GitHub Pages site (API: ${apiUrl}) ...`);
const result = spawnSync('npx next build', {
  cwd: buildDir,
  stdio: 'inherit',
  shell: true,
  env: {
    ...process.env,
    STATIC_EXPORT: '1',
    NEXT_DIST_DIR: '',
    HOSTIGER_DATABASE_URL: limitConnections(env.HOSTIGER_DATABASE_URL),
    ...(demo ? { NEXT_PUBLIC_STATIC_DEMO: '1' } : { NEXT_PUBLIC_API_URL: apiUrl }),
  },
});
if (result.status !== 0) process.exit(result.status ?? 1);

if (demo) await downloadImages();

// Without this GitHub Pages (Jekyll) hides the _next/ folder
writeFileSync(path.join(outDir, '.nojekyll'), '');
console.log(`\nGitHub Pages ${demo ? 'demo ' : ''}build ready in .pages-build/out`);

/** Demo: copy every uploaded image (/media/<file>) the saved data uses into out/media/. */
async function downloadImages() {
  const files = new Set();
  for (const file of Object.keys(DEMO_API)) {
    const text = readFileSync(path.join(outDir, 'demo-api', file), 'utf8');
    for (const m of text.matchAll(/\/media\/([A-Za-z0-9_-]+\.(?:jpg|jpeg|png|webp|gif|avif))/gi)) files.add(m[1]);
  }
  if (files.size === 0) return;

  const mediaDir = path.join(outDir, 'media');
  mkdirSync(mediaDir, { recursive: true });
  // The dev server keeps downloaded images here (lib/ftp.ts); reuse them
  const cacheDir = path.join(tmpdir(), 'exporio-media');
  const missing = [];
  for (const file of files) {
    const cached = path.join(cacheDir, file);
    if (existsSync(cached) && statSync(cached).size > 0) copyFileSync(cached, path.join(mediaDir, file));
    else missing.push(file);
  }

  if (missing.length) {
    const client = new Client(30_000);
    try {
      await client.access({
        host: (env.FTP_HOST ?? '').replace(/^ftps?:\/\//, ''),
        port: Number(env.FTP_PORT || 21),
        user: env.FTP_USER,
        password: env.FTP_PASSWORD,
        secure: false,
      });
      if (env.FTP_UPLOAD_DIR) await client.cd(env.FTP_UPLOAD_DIR);
      for (const file of missing) {
        try {
          await client.downloadTo(createWriteStream(path.join(mediaDir, file)), file);
        } catch (err) {
          rmSync(path.join(mediaDir, file), { force: true });
          console.warn(`  could not download image ${file}: ${err.message}`);
        }
      }
    } finally {
      client.close();
    }
  }
  console.log(`Saved ${readdirSync(mediaDir).length} of ${files.size} uploaded images into the demo`);
}
